routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CarreraController;
use App\Http\Controllers\DocenteController;
use App\Http\Controllers\MateriaController;
use App\Http\Controllers\inscripcionMateriaController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//ESTE TIENE QUE VER CON LA URL
Route::get('/', function () {
//     //ESTE TIENE QUE VER CON LO QUE SE MUESTRA , EN ESTE CASO UNA VISTA O EL ARCHIVO WELCOME.BLADE.PHP
    return view('welcome');
});

Route::get('/login', function () {
    return view('auth/login');
})->name('login');

Route::get('/register', function () {
    return view('auth/register');
})->name('register');

Route::resource('carrera', CarreraController::class);
Route::resource('materia', MateriaController::class);
Route::resource('docente', DocenteController::class);
Route::resource('inscripcion_materia',inscripcionMateriaController::class);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Carrera.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Carrera extends Model
{
    use HasFactory;
    //@TODO-CAMBIAR A USUARIO LOGUEADO
    protected $attributes=['created_by_id'=>1];
    protected $fillable = [
        'id','nombre','descripcion','estado','institucion','observaciones','tipo_carrera_id',
'tipo_formacion_id','modalidad_dictado_id','condicion_ingreso_id','created_at','created_by_id',
'updated_at','updated_by_id','deleted_at','deleted_by_id'
    ];

    protected $table = 'carrera';
}

app/Http/Controllers/CarreraController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\Carrera;

class CarreraController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Carrera::latest()->paginate(5);
    
        return view('carrera.index',compact('data'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    // {    $carrera=Carrera::all();
    {    $carrera=Carrera::select('estado')->distinct()->get();

        return view('carrera.create',compact('carrera'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $request->validate([
            'nombre' => 'required',
            'descripcion' => 'required',
            'estado' => 'required',
        ]);

        Carrera::create($request->all());
     
        return redirect()->route('carrera.index')
                        ->with('success','Carrera creada satisfactoriamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Carrera  $carrera
     * @return \Illuminate\Http\Response
     */
    public function show(Carrera $carrera)
    {
        return view('carrera.show',compact('carrera'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Carrera  $carrera
     * @return \Illuminate\Http\Response
     */
    public function edit(Carrera $carrera)
    {
        return view('carrera.edit',compact('carrera'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Carrera  $carrera
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Carrera $carrera)
    {
        $request->validate([
            //'id' => 'required',
            'nombre' => 'required',
            'descripcion' => 'required',
            //'estado' => 'required',
        ]);
    
        $carrera->update($request->all());
    
        return redirect()->route('carrera.index')
                        ->with('success','Carrera actualizada satisfactoriamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Carrera  $carrera
     * @return \Illuminate\Http\Response
     */
    public function destroy(Carrera $carrera)
    {
        $carrera->delete();
    
        return redirect()->route('carrera.index')
                        ->with('success','Carrera eliminada satisfactoriamente');
    }
}

resources/views/carrera/create.blade.php
@extends('layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <br>
            <h2>Ingresar nueva Carrera</h2>
        </div>
        <div class="pull-right">
            <br>
            <a class="btn btn-primary" href="{{ route('carrera.index') }}"> Atrás</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Hay algunos problemas con lo que ingresaste.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('carrera.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre:</strong>
                <input type="text" name="nombre" class="form-control" placeholder="Ingresar nombre">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Descripción:</strong>
                <textarea class="form-control" style="height:150px" name="descripcion" placeholder="Ingresar descripción"></textarea>
            </div>
        </div>
        {{-- <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Estado:</strong>
                <input type="text" name="estado" class="form-control" placeholder="Ingresar Estado:">
            </div>
        </div> --}}
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <label >Estado</label>
            <select class="form-control" name="estado">
              @foreach ($carrera as $carrera)
              <option value="{{$carrera->estado}}">{{$carrera->estado}}</option>
                  
              @endforeach
            </select>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Institución:</strong>
                <input type="text" name="institucion" class="form-control" placeholder="Ingresar institución">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Observaciones:</strong>
                <textarea class="form-control" style="height:150px" name="observaciones" placeholder="Ingresar observación"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tipo de carrera id:</strong>
                <input type="numb" name="tipo_carrera_id" class="form-control" placeholder="Ingresar tipo de carrera id">
            </div>
        </div>
       
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tipo de Formación:</strong>
                <input type="numb" name="tipo_formacion_id" class="form-control" placeholder="Ingresar id">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Modalidad dictado id:</strong>
                <input type="numb" name="modalidad_dictado_id" class="form-control" placeholder="Ingresar modalidad dictado id">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Condicion ingreso id:</strong>
                <input type="numb" name="condicion_ingreso_id" class="form-control" placeholder="Ingresar condición ingreso id">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/carrera/edit.blade.php
@extends('layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <br>
                <h2>Editar Carrera</h2>
            </div>
            <div class="pull-right">
                <br>
                <a class="btn btn-primary" href="{{ route('carrera.index') }}"> Atrás</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> Hay algunos problemas con lo que ingresaste.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('carrera.update',$carrera->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Nombre:</strong>
                    <input type="text" name="nombre" value="{{ $carrera->nombre }}" class="form-control" placeholder="nombre">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Descripción:</strong>
                    <textarea class="form-control" style="height:150px" name="descripcion" placeholder="descripcion">{{ $carrera->descripcion }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Estado:</strong>
                    <input type="text" name="estado" value="{{ $carrera->estado }}" class="form-control" placeholder="estado">
                </div>
            </div>
            {{-- <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                <label >Estado</label>
                <select class="form-control" name="estado">
                  @foreach ($carrera as $carrera)
                  <option value="{{$carrera->estado}}"></option>
                      
                  @endforeach
                </select> --}}
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Institución:</strong>
                    <input type="text" name="institucion" value="{{ $carrera->institucion }}" class="form-control" placeholder="institucion">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Observaciones:</strong>
                  <input type="text" name="observaciones" value="{{ $carrera->observaciones }}" class="form-control" placeholder="observaciones">
              </div>
          </div>
            {{-- <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Nombre:</strong>
                    <input type="text" name="nombre" value="{{ $carrera->nombre }}" class="form-control" placeholder="Title">
                </div>
            </div> --}}
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Tipo de carrera id:</strong>
                    <input type="text" name="tipo_carrera_id" value="{{ $carrera->tipo_carrera_id }}" class="form-control" placeholder="Tipo de carrera id">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Tipo de formacion id:</strong>
                    <input type="text" name="tipo_formacion_id" value="{{ $carrera->tipo_formacion_id }}" class="form-control" placeholder="Tipo de formacion id">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Modalidad dictado id:</strong>
                    <input type="text" name="modalidad_dictado_id" value="{{ $carrera->modalidad_dictado_id }}" class="form-control" placeholder="Modalidad dictado id">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Condición de ingreso id:</strong>
                    <input type="text" name="condicion_ingreso_id" value="{{ $carrera->condicion_ingreso_id }}" class="form-control" placeholder="Condición de ingreso id">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/carrera/index.blade.php
@extends('layout')
 
@section('content')
    <div class="row" style="margin-top: 5rem;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Listado de Carreras</h2>
                <br>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('carrera.create') }}"> Nueva Carrera</a>
                <br>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Estado</th>
            <th>Institución</th>
            <th>Observaciones</th>
            <th>Tipo de Carrera id</th>
            <th>Tipo de Formación id</th>
            <th>Modalidad de dictado id</th>
            <th>Condición ingreso id</th>
            <th width="280px">Acción</th>
        </tr>
        @foreach ($data as $key => $value)
        <tr>
            <td>{{ $value->id }}</td> <!––PRIMERA COLUMNA––>
            <td>{{ $value->nombre }}</td> <!––SEGUNDA COLUMNA––>
            <td>{{ \Str::limit($value->descripcion, 100) }}</td>
            <td>{{ $value->estado }}</td> 
            <td>{{ $value->institucion }}</td> 
            <td>{{ \Str::limit($value->observaciones, 100) }}</td>
            <td>{{ $value->tipo_carrera_id }}</td> 
            <td>{{ $value->tipo_formacion_id }}</td> 
            <td>{{ $value->modalidad_dictado_id }}</td>
            <td>{{ $value->condicion_ingreso_id }}</td> 
            <td>
                <form action="{{ route('carrera.destroy',$value->id) }}" method="POST">   
                    <a class="btn btn-info" href="{{ route('carrera.show',$value->id) }}">Ver</a>    
                    <a class="btn btn-primary" href="{{ route('carrera.edit',$value->id) }}">Editar</a>   
                    @csrf
                    @method('DELETE')      
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>  
    {!! $data->links('pagination::bootstrap-4') !!}
@endsection

resources/views/carrera/show.blade.php
@extends('layout')
  
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <br>
                <h2> Ver Carrera</h2>
            </div>
            <div class="pull-right">
                <br>
                <a class="btn btn-primary" href="{{ route('carrera.index') }}"> Atrás</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre:</strong>
                {{ $carrera->nombre }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Descripción:</strong>
                {{ $carrera->descripcion }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Estado:</strong>
               {{ $carrera->estado }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Institución:</strong>
               {{ $carrera->institucion }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
              <strong>Observaciones:</strong>
              {{ $carrera->observaciones }}
          </div>
      </div>
        {{-- <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
              <strong>Observaciones:</strong>
              <input type="text" name="observaciones" value="{{ $carrera->observaciones }}" class="form-control" placeholder="observaciones">
          </div>
      </div> --}}
        {{-- <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre:</strong>
                <input type="text" name="nombre" value="{{ $carrera->nombre }}" class="form-control" placeholder="Title">
            </div>
        </div> --}}
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tipo de carrera id:</strong>
                {{ $carrera->tipo_carrera_id }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Tipo de formación id:</strong>
                {{ $carrera->tipo_formacion_id }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Modalidad dictado id:</strong>
                {{ $carrera->modalidad_dictado_id }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Condición de ingreso id:</strong>
                {{ $carrera->condicion_ingreso_id }}
            </div>
        </div>
    </div>
@endsection