routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CarreraController;
use App\Http\Controllers\DocenteController;
use App\Http\Controllers\MateriaController;
use App\Http\Controllers\inscripcionMateriaController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//ESTE TIENE QUE VER CON LA URL
Route::get('/', function () {
//     //ESTE TIENE QUE VER CON LO QUE SE MUESTRA , EN ESTE CASO UNA VISTA O EL ARCHIVO WELCOME.BLADE.PHP
    return view('welcome');
});

Route::get('/login', function () {
    return view('auth/login');
})->name('login');

Route::get('/register', function () {
    return view('auth/register');
})->name('register');

Route::resource('carrera', CarreraController::class);
Route::resource('materia', MateriaController::class);
Route::resource('docente', DocenteController::class);
Route::resource('inscripcion_materia',inscripcionMateriaController::class);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/inscripcion_materia.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class inscripcion_materia extends Model
{
    use HasFactory;
    protected $fillable = [
      'materia_id','alumno_id','carrera_id',
      ];
      protected $table = 'inscripcion_materia';
}

app/Http/Controllers/InscripcionMateriaController.php
<?php

namespace App\Http\Controllers;

use App\Models\inscripcion_materia;
use App\Models\Materia;
use App\Models\Carrera;
use Illuminate\Http\Request;

class InscripcionMateriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $data = inscripcion_materia::latest()->paginate(5);
    
      return view('inscripcion_materia.index',compact('data'))
          ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response**
     */
    public function create()
    {
    $inscripcion_materia=inscripcion_materia::all();
    $carrera=Carrera::all();
    $materia=Materia::all();

        return view('inscripcion_materia.create',compact('inscripcion_materia','materia','carrera'))
        
        
;
        
    }

    /*
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
      $request->validate([
        // 'materia_id' => 'required',
    ]);

    // Materia::create($request->all());
    // Carrera::create($request->all());
    inscripcion_materia::create($request->all());
    return redirect()->route('inscripcion_materia.index')
                    ->with('success','inscripción a materia creada satisfactoriamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\inscripcion_materia  $inscripcion_materia
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
      
      $inscripcion_materia=inscripcion_materia::findOrfail($id);
        return view('inscripcion_materia.show',compact('inscripcion_materia'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\inscripcion_materia  $inscripcion_materia
     * @return \Illuminate\Http\Response
     */
    public function edit($id) { 
      
      $inscripcion_materia=inscripcion_materia::findOrfail($id);
      return view('inscripcion_materia.edit',compact('inscripcion_materia'));
}
    

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\inscripcion_materia  $inscripcion_materia
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

      $inscripcion_materia = request()->except(['_token','_method']);
      inscripcion_materia::where('id','=',$id)->update($inscripcion_materia);

      $inscripcion_materia=inscripcion_materia::findOrfail($id);
      return redirect()->route('inscripcion_materia.index')
      ->with('success','Inscripción actualizada satisfactoriamente');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\inscripcion_materia  $inscripcion_materia
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      inscripcion_materia::destroy($id);

      return redirect()->route('inscripcion_materia.index')
                      ->with('success','Inscripcion eliminada satisfactoriamente');
    }
}

resources/views/inscripcion_materia/create.blade.php
@extends('layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <br>
            <h2>Ingresar Nueva Inscripción</h2>
        </div>
        <div class="pull-right">
            <br>
            <a class="btn btn-primary" href="{{ route('inscripcion_materia.index') }}"> Atrás</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Hay algunos problemas con lo que ingresaste.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('inscripcion_materia.store') }}" method="POST">
    @csrf
  
    {{-- <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12"> --}}
          {{-- <div class="form-group">
                <strong>Materia:</strong>
                <input type="text" name="materia_id" class="form-control" placeholder="Ingresar materia">

            </div>
        </div>  --}}
        
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Alumno:</strong>
                <input type="text" name="alumno_id" class="form-control" placeholder="Ingresar alumno">
            </div>
        </div> 
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
              <strong>Materia:</strong>
              <input type="text" name="materia_id" class="form-control" placeholder="Ingresar materia">
          </div>
      </div> 
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Carrera:</strong>
            <input type="text" name="carrera_id" class="form-control" placeholder="Ingresar carrera">
        </div>
    </div> 


        {{-- <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <label >Materia</label>
            <select class="form-control" name="id">
              @foreach ($materia as $materia)
              <option value="{{$materia->id}}">{{$materia->id}}</option>
                  
              @endforeach
            </select> --}}
        
        
        {{-- <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <label >Carrera</label>
            <select class="form-control" name="id">
              @foreach ($carrera as $carrera)
              <option value="{{$carrera->id}}">{{$carrera->id}}</option>
                  
              @endforeach
            </select>
        --}}
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/inscripcion_materia/edit.blade.php
@extends('layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <br>
                <h2>Editar inscripción</h2>
            </div>
            <div class="pull-right">
                <br>
                <a class="btn btn-primary" href="{{ route('inscripcion_materia.index') }}"> Atrás</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> Hay algunos problemas con lo que ingresaste.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('inscripcion_materia.update',$inscripcion_materia->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Materia:</strong>
                    <input type="text" name="materia_id" value="{{ $inscripcion_materia->materia_id }}" class="form-control" placeholder="estado">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Alumno:</strong>
                    <input type="text" name="alumno_id" value="{{ $inscripcion_materia->alumno_id }}" class="form-control" placeholder="alumno_id">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Carrera:</strong>
                    <input type="text" name="carrera_id" value="{{ $inscripcion_materia->carrera_id }}" class="form-control" placeholder="carrera_id">
                </div>
            </div>
            {{-- <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Creado por:</strong>
                    <input type="text" name="created_by_id" value="{{ $inscripcion_materia->created_by_id  }}" class="form-control" placeholder="institucion">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Modificado por:</strong>
                    <input type="text" name="updated_by_id" value="{{ $inscripcion_materia->updated_by_id }}" class="form-control" placeholder="Title">
                </div>
            </div> --}}
            
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/inscripcion_materia/index.blade.php
@extends('layout')
 
@section('content')
    <div class="row" style="margin-top: 5rem;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Inscripción a Materias</h2>
                <br>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('inscripcion_materia.create') }}"> Nueva inscripción</a>
                <br>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>Id</th>
            <th>Materia</th>
            <th>Alumno</th>
            <th>Carrera</th>
            
            
            <th width="280px">Acción</th>
        </tr>
        @foreach ($data as $key => $value)
        <tr>
            <td>{{ $value->id }}</td> <!––PRIMERA COLUMNA––>
            <td>{{ $value->materia_id }}</td> <!––SEGUNDA COLUMNA––>
            <td>{{ $value->alumno_id }}</td> 
            <td>{{ $value->carrera_id }}</td> 
            
            <td>
                <form action="{{ route('inscripcion_materia.destroy',$value->id) }}" method="POST">   
                    <a class="btn btn-info" href="{{ route('inscripcion_materia.show',$value->id) }}">Ver</a>    
                    <a class="btn btn-primary" href="{{ route('inscripcion_materia.edit',$value->id) }}">Editar</a>   
                    @csrf
                    @method('DELETE')      
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>  
    {!! $data->links('pagination::bootstrap-4') !!}
@endsection

resources/views/inscripcion_materia/show.blade.php
@extends('layout')
  
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <br>
                <h2> Ver inscripción</h2>
            </div>
            <div class="pull-right">
                <br>
                <a class="btn btn-primary" href="{{ route('inscripcion_materia.index') }}"> Atrás</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Materia:</strong>
                {{ $inscripcion_materia->materia_id }}
            </div>
        </div>
       
        <div class="row">
          
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Alumno:</strong>
               {{ $inscripcion_materia->alumno_id }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Carrera:</strong>
               {{ $inscripcion_materia->carrera_id }}
            </div>
        </div>
        @endsection