routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CarreraController;
use App\Http\Controllers\DocenteController;
use App\Http\Controllers\MateriaController;
use App\Http\Controllers\inscripcionMateriaController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//ESTE TIENE QUE VER CON LA URL
Route::get('/', function () {
//     //ESTE TIENE QUE VER CON LO QUE SE MUESTRA , EN ESTE CASO UNA VISTA O EL ARCHIVO WELCOME.BLADE.PHP
    return view('welcome');
});

Route::get('/login', function () {
    return view('auth/login');
})->name('login');

Route::get('/register', function () {
    return view('auth/register');
})->name('register');

Route::resource('carrera', CarreraController::class);
Route::resource('materia', MateriaController::class);
Route::resource('docente', DocenteController::class);
Route::resource('inscripcion_materia',inscripcionMateriaController::class);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Materia.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Materia extends Model

{
    use HasFactory;
    public $timestamps = false;

    protected $fillable = [
        'id','codigo','nombre','descripcion','anio','comision','carrera_id','docente_id'
    ];

    protected $table = 'materia';
    
    /**
     * Get the Docente that owns the Materia.
     */
    public function docente()
    {
        return $this->belongsTo(Docente::class);
    }

    /**
     * Get the Carrera that owns the Materia.
     */
    public function carrera()
    {
        return $this->belongsTo(Carrera::class);
    }
}

app/Http/Controllers/MateriaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Carrera;
use App\Models\Docente;
use Illuminate\Http\Request;
use App\Models\Materia;

class MateriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Materia::paginate(20);
    
        return view('materia.index',compact('data'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {        
        $carreras = Carrera::all();
        $docentes = Docente::all();

        return view('materia.create', compact('carreras', 'docentes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
        'codigo' => 'required',
        'nombre' => 'required',
    ]);

    Materia::create($request->all());

    return redirect()->route('materia.index')
                    ->with('success','materia creada satisfactoriamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Materia  $materia
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
      
      $materia=Materia::findOrfail($id);
        return view('materia.show',compact('materia'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Materia  $materia
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $materia = Materia::findOrfail($id);
        $carreras = Carrera::all();
        $docentes = Docente::all();

        return view('materia.edit', compact('materia', 'carreras', 'docentes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Materia  $materia
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

      $datosMateria = request()->except(['_token','_method']);
      Materia::where('id','=',$id)->update($datosMateria);

      $materia=Materia::findOrfail($id);
      return redirect()->route('materia.index')
      ->with('success','Materia actualizada satisfactoriamente');

    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Materia  $materia
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      materia::destroy($id);

      return redirect()->route('materia.index')
                      ->with('success','Materia eliminada satisfactoriamente');
    }
}

resources/views/materia/create.blade.php
@extends('layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <br>
            <h2>Ingresar nueva Materia</h2>
        </div>
        <div class="pull-right">
            <br>
            <a class="btn btn-primary" href="{{ route('materia.index') }}"> Atrás</a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong>Hay algunos problemas con lo que ingresaste.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('materia.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Código:</strong>
                <input type="text" name="codigo" class="form-control" placeholder="Ingresar código">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Nombre:</strong>
              <input type="text" name="nombre" class="form-control" placeholder="Ingresar nombre">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
              <strong>Descripción:</strong>
              <textarea class="form-control" style="height:150px" name="descripcion" placeholder="Ingresar descripción"></textarea>
          </div>
      </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Año:</strong>
                {{-- <input type="number"  name="anio" min="1" max="3">  --}}
                <input type="number" name="anio" min="1" max="3" class="form-control" placeholder="Ingresar año">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Comisión:</strong>
              <input type="text" name="comision" class="form-control" placeholder="Ingresar comisión">
            </div>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <strong>Carrera:</strong>
            <select class="form-control" name="carrera_id">
              <option value="">---Seleccione---</option>
              @foreach ($carreras as $carrera)
              <option value="{{ $carrera->id }}">{{ $carrera->nombre }}</option>
              @endforeach
            </select>
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Docente:</strong>
                <select class="form-control" name="docente_id">
                    <option value="">---Seleccione---</option>
                    @foreach ($docentes as $docente)
                    <option value="{{ $docente->id }}">{{ $docente->getNombreCompleto() }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        
        
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/materia/edit.blade.php
@extends('layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <br>
                <h2>Editar Materia</h2>
            </div>
            <div class="pull-right">
                <br>
                <a class="btn btn-primary" href="{{ route('materia.index') }}"> Atrás</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> Hay algunos problemas con lo que ingresaste.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('materia.update',$materia->id) }}" method="POST">
        @csrf
        {{@method_field('PATCH')}}

   
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Código:</strong>
              <input type="text" name="codigo" value="{{ $materia->codigo }}" class="form-control" placeholder="codigo">
              </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Nombre:</strong>
              <input type="text" name="nombre" value="{{ $materia->nombre }}" class="form-control" placeholder="nombre">
              </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                  <strong>Descripción:</strong>
                  <input type="text" name="descripcion" value="{{ $materia->descripcion }}" class="form-control" placeholder="descripcion">
                </div>
              </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                <strong>Año:</strong>
                <input type="text" name="anio" value="{{ $materia->anio }}" class="form-control" placeholder="anio">
              </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                <strong>Comisión:</strong>
                <input type="text" name="comision" value="{{ $materia->comision }}" class="form-control" placeholder="comision">
              </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                <strong>Tipo de carrera id:</strong>
                <select class="form-control" name="carrera_id">
                    <option value="">---Seleccione---</option>
                    @foreach ($carreras as $carrera)
                        @if ($carrera->id == $materia->carrera_id)
                        <option selected="selected" value="{{ $carrera->id }}">{{ $carrera->nombre }}</option>
                        @else
                        <option value="{{ $carrera->id }}">{{ $carrera->nombre }}</option>
                        @endif
                    @endforeach
                </select>
              </div>
          </div>
          <div class="col-xs-12 col-sm-12 col-md-12">
              <div class="form-group">
                <strong>Docente id:</strong>
                <select class="form-control" name="docente_id">
                    <option value="">---Seleccione---</option>
                    @foreach ($docentes as $docente)
                        @if ($docente->id == $materia->docente_id)
                        <option selected="selected" value="{{ $docente->id }}">{{ $docente->getNombreCompleto() }}</option>
                        @else
                        <option value="{{ $docente->id }}">{{ $docente->getNombreCompleto() }}</option>
                        @endif
                    @endforeach
                </select>
              </div>
          </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/materia/index.blade.php
@extends('layout')
 
@section('content')
    <div class="row" style="margin-top: 5rem;">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Listado de Materias</h2>
                <br>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('materia.create') }}"> Nueva materia</a>
                <br>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
           <th>Id</th>
            <th>Código</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Año</th>
            <th>Comisión</th>
            <th>Carrera</th>
            <th>Docente</th>
            <th width="280px">Acción</th>
        </tr>
        @foreach ($data as $key => $value)
        <tr>
            <td>{{ $value->id }}</td> <!––PRIMERA COLUMNA––>
            <td>{{ $value->codigo }}</td> <!––SEGUNDA COLUMNA––>
            <td>{{ $value->nombre }}</td> <!––SEGUNDA COLUMNA––>
            <td>{{ ($value->descripcion) }}</td>
            <td>{{ $value->anio }}</td> 
            <td>{{ $value->comision }}</td> 
            <td>{{ $value->carrera->nombre }}</td> 
            <td>{{ $value->docente ? $value->docente->getNombreCompleto() : '' }}</td> 
            <td>
                <form action="{{ route('materia.destroy',$value->id) }}" method="POST">   
                    <a class="btn btn-info" href="{{ route('materia.show',$value->id) }}">Ver</a>    
                    <a class="btn btn-primary" href="{{ route('materia.edit',$value->id) }}">Editar</a>   
                    @csrf
                    @method('DELETE')      
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>  
    {!! $data->links('pagination::bootstrap-4') !!}
@endsection

resources/views/materia/show.blade.php
@extends('layout')
  
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <br>
                <h2> Ver Materia</h2>
            </div>
            <div class="pull-right">
                <br>
                <a class="btn btn-primary" href="{{ route ('materia.index') }}"> Atrás</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Código:</strong>
                {{ $materia->codigo}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
              <strong>Nombre:</strong>
              {{ $materia->nombre }}  </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
              <strong>Descripción:</strong>
              {{ $materia->descripcion }}          </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
          <strong>Año:</strong>
          {{ $materia->anio }}
          </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Comisión:</strong>
       {{ $materia->comision }}
        </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Carrera:</strong>
      {{ $materia->carrera->nombre }}
      </div>
</div><div class="col-xs-12 col-sm-12 col-md-12">
  <div class="form-group">
    <strong>Docente:</strong>
   {{ $materia->docente->getNombreCompleto() }}
      </div>
</div>
    </div>
@endsection